(() => {
const D=window.GENEVIEVE_DATA; const $=id=>document.getElementById(id);
const pantry=JSON.parse(localStorage.getItem('gen_pantry_v1')||'{}');
const prices=JSON.parse(localStorage.getItem('gen_prices_v1')||'{}');
const controls=['householdSize','mealBudget','mealType','vegetarian','gf','df','lunchbox','freezer','onePot'];
let current=[];
const save=()=>{localStorage.setItem('gen_pantry_v1',JSON.stringify(pantry));localStorage.setItem('gen_prices_v1',JSON.stringify(prices));};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>Number(x)||0; const money=x=>'$'+Number(x||0).toFixed(2); const pct=x=>Math.round((x||0)*100)+'%';
function settings(){return {size:Math.max(1,num($('householdSize').value)),budget:Math.max(0,num($('mealBudget').value)),meal:$('mealType').value,veg:$('vegetarian').value,gf:$('gf').value,df:$('df').value,lunchbox:$('lunchbox').value,freezer:$('freezer').value,onePot:$('onePot').value};}
function pass(r,s){return (s.meal==='Any'||r.mealType===s.meal)&&(s.veg==='No restriction'||r.vegetarian==='Yes')&&(s.gf==='No restriction'||r.gfAdaptable==='Yes')&&(s.df==='No restriction'||r.dfAdaptable==='Yes')&&(s.lunchbox==='No restriction'||r.lunchbox==='Yes')&&(s.freezer==='No restriction'||r.freezer==='Yes')&&(s.onePot==='No restriction'||r.onePot==='Yes');}
function assess(r,s){const scale=s.size/r.baseServes; let req=0,covered=0,missing=0,cost=0,pricingComplete=true; const lines=[];
 r.ingredients.forEach(i=>{const required=i.optional?0:i.baseQty*scale; const key=i.ingredient+'|'+i.unit; const have=num(pantry[key]); const shortage=Math.max(0,required-have); const price=num(prices[key]); if(!i.optional){req++; if(shortage<=1e-9)covered++; else {missing++; if(price<=0)pricingComplete=false; cost+=shortage*price;}}
 lines.push({...i,required,have,shortage,price,missingCost:shortage*price});});
 const coverage=req?covered/req:1; const budgetScore=pricingComplete?(cost<=s.budget?30:Math.max(0,30*(1-cost/Math.max(s.budget,.01)))):0; const score=coverage*60+budgetScore+(missing===0?10:Math.max(0,10-missing));
 const budgetStatus=!pricingComplete?'Need prices':(cost<=s.budget?'Within budget':'Over budget'); const action=missing===0?'Cook now':(!pricingComplete?'Enter prices for missing ingredients':budgetStatus==='Within budget'?`Buy ${missing} missing ingredient line${missing===1?'':'s'}`:'Use swaps or choose another recipe');
 return {recipe:r,scale,lines,coverage,missing,cost,pricingComplete,budgetStatus,score,action}; }
function rank(){const s=settings(); current=D.recipes.filter(r=>pass(r,s)).map(r=>assess(r,s)).sort((a,b)=>b.score-a.score||b.coverage-a.coverage||a.recipe.name.localeCompare(b.recipe.name)); renderResults(current);}
function renderResults(rows){$('eligibleKpi').textContent=rows.length;$('cookNowKpi').textContent=rows.filter(x=>x.missing===0).length;$('budgetKpi').textContent=rows.filter(x=>x.pricingComplete&&x.cost<=settings().budget).length;
 $('results').innerHTML=rows.slice(0,30).map((x,i)=>{const r=x.recipe; const tag=x.missing===0?'good':x.budgetStatus==='Within budget'?'good':x.budgetStatus==='Need prices'?'warn':'bad';return `<article class="recipe-card"><div class="recipe-top"><div><div class="rank">#${i+1} · score ${x.score.toFixed(1)}</div><h3>${esc(r.name)}</h3></div><span class="tag ${tag}">${esc(x.budgetStatus)}</span></div><div class="tags"><span class="tag">${esc(r.mealType)}</span>${r.freezer==='Yes'?'<span class="tag">Freezer</span>':''}${r.lunchbox==='Yes'?'<span class="tag">Lunchbox</span>':''}${r.vegetarian==='Yes'?'<span class="tag">Vegetarian</span>':''}</div><div class="scorebar"><i style="width:${Math.min(100,x.score)}%"></i></div><div class="stats"><div class="stat">Pantry<b>${pct(x.coverage)}</b></div><div class="stat">Missing<b>${x.missing}</b></div><div class="stat">Gap cost<b>${x.pricingComplete?money(x.cost):'—'}</b></div></div><div class="card-action"><span class="action-text">${esc(x.action)}</span><button class="view-btn" data-id="${r.id}">View meal</button></div></article>`}).join('');
 document.querySelectorAll('.view-btn').forEach(b=>b.onclick=()=>openRecipe(b.dataset.id));}
function renderEntryList(kind,query=''){const store=kind==='pantry'?pantry:prices; const list=$(kind==='pantry'?'pantryList':'priceList'); const q=query.toLowerCase().trim(); const rows=D.ingredientUnitPairs.filter(p=>!q||p.ingredient.toLowerCase().includes(q)||p.unit.toLowerCase().includes(q)).slice(0,180); list.innerHTML=rows.map(p=>`<div class="entry-row"><div><div class="entry-name">${esc(p.ingredient)}</div><div class="entry-unit">recipe unit: ${esc(p.unit)}</div></div><input type="number" min="0" step="0.01" value="${store[p.key]||''}" data-key="${esc(p.key)}" placeholder="0"></div>`).join(''); list.querySelectorAll('input').forEach(inp=>inp.onchange=()=>{const v=num(inp.value);if(v>0)store[inp.dataset.key]=v;else delete store[inp.dataset.key];save();updateCounts();rank();});}
function updateCounts(){$('pantryCount').textContent=Object.keys(pantry).length+' entered';$('priceCount').textContent=Object.keys(prices).length+' priced';}
function openRecipe(id){const x=current.find(a=>a.recipe.id===id)||assess(D.recipes.find(r=>r.id===id),settings()); const r=x.recipe; const method=r.method.split(' | ').map(s=>s.replace(/^\d+\.\s*/,'')); const rows=x.lines.map(i=>{const sw=D.swapMap[i.swapGroup]||[];return `<div class="ingredient-line ${i.shortage<=1e-9?'have':'missing'}"><span><b>${esc(i.ingredient)}</b>${sw.length?`<div class="swap-note">Swap ideas: ${sw.slice(0,5).map(esc).join(', ')}</div>`:''}</span><span>Need<br><b>${i.required.toFixed(2)} ${esc(i.unit)}</b></span><span>Have<br><b>${i.have.toFixed(2)}</b></span><span>Short<br><b>${i.shortage.toFixed(2)}</b>${i.shortage>0&&i.price>0?`<br>${money(i.missingCost)}`:''}</span></div>`}).join('');
 $('recipeDetail').innerHTML=`<div class="detail"><h2>${esc(r.name)}</h2><div class="detail-sub">${esc(r.mealType)} · base serves ${r.baseServes} · scaled for ${settings().size} · prep ${r.prepMin} min · cook ${r.cookMin} min</div><div class="budget-note"><b>${pct(x.coverage)} pantry coverage</b> · ${x.missing} missing required line${x.missing===1?'':'s'} · ${x.pricingComplete?`estimated shopping gap ${money(x.cost)}`:'some missing ingredients still need prices'} · <b>${esc(x.budgetStatus)}</b></div>${!x.pricingComplete?'<div class="warning">Affordability is not claimed until every missing required ingredient has a price. GENEVIEVE does not guess prices.</div>':''}<div class="detail-grid"><div class="detail-box"><h3>Scaled ingredients</h3>${rows}</div><div class="detail-box"><h3>Method</h3><ol class="method-list">${method.map(m=>`<li>${esc(m)}</li>`).join('')}</ol><h3>Mix & change</h3><p>${esc(r.swapNotes||'Use the Swap Matrix options shown beside ingredients.')}</p></div></div></div>`; $('recipeDialog').showModal();}
$('closeDialog').onclick=()=>$('recipeDialog').close();$('rankBtn').onclick=rank; controls.forEach(id=>$(id).onchange=rank);$('pantrySearch').oninput=e=>renderEntryList('pantry',e.target.value);$('priceSearch').oninput=e=>renderEntryList('price',e.target.value);$('clearPantry').onclick=()=>{if(confirm('Clear all pantry quantities?')){Object.keys(pantry).forEach(k=>delete pantry[k]);save();renderEntryList('pantry',$('pantrySearch').value);updateCounts();rank();}};$('clearPrices').onclick=()=>{if(confirm('Clear all saved prices?')){Object.keys(prices).forEach(k=>delete prices[k]);save();renderEntryList('price',$('priceSearch').value);updateCounts();rank();}};
$('recipeCount').textContent=D.recipes.length;renderEntryList('pantry');renderEntryList('price');updateCounts();rank();
})();